blank_issues_enabled: false
contact_links:
  - name: Epidemic Help
    url: https://torpkev.github.io/epidemic_docs/
    about: Help pages
  - name: Discord
    url: https://discord.gg/7a47xSX
    about: Join us on Discord
