# ==================================================================================
#                                    Epidemic
#                     Bringing real survival to your server
#                  Visit our Discord - https://discord.gg/7a47xSX
# ==================================================================================

# ==================================================================================
# Plugin Settings
# ==================================================================================
# Most recent run version of the plugin.  DO NOT CHANGE THIS MANUALLY, it is used
# to decide if configuration changes should be made between versions.  Modifying
# it could cause configuration instability when updating versions and will NOT
# be supported.
v: 1.6.8.7
# Afflicted time is the number of seconds that elapse between checking for
# infectious illnesses.  Default is 60
afflicted_time: 60
# Symptom time is the number of seconds that elapse between applying symtoms
# when a player has an ailment.  Default is 20
symptom_time: 20
# ==================================================================================
# Ailment Settings
# ==================================================================================
# Flag to indicate if the illness should be cleared on death
clear_ailment_on_death: true
# The radius in which you are contagious
contagious_radius: 5
# The height in which you are contagious
contagious_height: 3
# This is the number ailment checks are run against, 10000 by default, meaning every
# time an ailment check is done (scheduled or via an event such as a burn or fall),
# it checks 1-10000.  If your players random number is <= your ailment chance (either
# infectious or non-infectious) your player will get sick.  To lower your chances of
# a player receiving an ailment, you can increase random_chance, or lower the chances
# in the config file.
random_chance: 10000

# If true, prevent_ailment_worldguard_pvp_deny will prevent players receiving symptoms or new ailments
# while in a WorldGuard region that does not allow PVP
prevent_ailment_worldguard_pvp_deny: true

# ==================================================================================
# Syringe - THIS WILL BE MOVED TO ITS OWN CONFIG IN A FUTURE VERSION
# Deprecated in this file as of 1.6.5
# ==================================================================================
# Display name of an empty syringe
empty_syringe_name: '&aEmpty Syringe'
# Display name of a full syringe
full_syringe_name: '&aFull Syringe'
# Ingredients for syringe (see relief_ingredients for usage)
syringe_ingredients:
  B: GLASS_BOTTLE
  L: LEVER
# Recipe for syringe (see relief_shape for usage)
syringe_shape:
  TOP: .L.
  MIDDLE: .B.
  BOTTOM: '...'
# The text displayed to the player when they use a syringe while sick.  <%ailment%> can
# be used to display the actual illness name
syringe_use_sick: You carefully draw some blood, tainted with <%ailment%> from your arm
# The text displayed to the player when they usage a syringe but didn't need to
syringe_use_not_sick: You fill the syringe with blood, but your can't do anything with it
# ==================================================================================
# Crafting
# ==================================================================================
# auto_discover_recipes is a true/false flag that if set will add the custom items from
# Epidemic into the players recipe book.  If not set, the player will need to discover
# the recipe manually.
auto_discover_recipes: false
# ==================================================================================
# Thirst
# ==================================================================================
# Flag to indicate if thirst should be enabled
enable_thirst: true
# Number of seconds to check for thirst (time per cycle for symptoms)
thirst_seconds: 30
# List of worlds to not apply thirst to
prevent_thirst_worlds:
- world_nether
# dirty_water_penalty is a flag to indicate if a penalty should be applied for drinking dirty water
dirty_water_penalty: true
# dirty_water_chance is the chance that drinking non-boiled water could cause illness
# This number is added to the environment modifier.  A random chance will be applied against this
# number and can cause illness.  dirty_water_chance should be 0-1000
dirty_water_chance: 50
# respawn thirst level
respawn_thirst_level: 20
# Flag to disable drinking from a cauldron
disable_cauldron: false
# Flag to disable water bowls (drinking from a pool)
disable_water_bowl: false
# Flag to disable drinking water with your hands (drinking from a pool)
disable_water_hands: false
# If true, the thirst bar is displayed on screen
use_thirst_bar: true
# If true, running /thirst will return thirst text instead of usage
use_thirst_text: false
# If true, the player will receive warnings about being thirsty
display_thirst_warning: true
# If true, when the player drinks they will receive a notification in the action bar
display_drink_notification: false
# ==================================================================================
# Temperature
# ==================================================================================
# Flag to indicate if temperature should be enabled
enable_temp: true
# Number of seconds to check for temperature (time per cycle for symptoms)
temp_seconds: 30
# List of worlds to not apply temperature to
prevent_temp_worlds:
- 'world_nether'
- 'world_the_end'
# Number of seconds to have temperature relief applied for
temp_relief_time: 60
# Flag to indicate if players should be warned about temperature extremes
temp_warn_players: true
# ==================================================================================
# Debug
# ==================================================================================
debug_logging: false
debug_to_file: false
